import { test, expect, chromium } from '@playwright/test';
import fs from 'node:fs/promises';

test('gym-wave2-floor_items: ghost, plane drag, snap, rotate, Escape, undo, inspector, Save and GLB', async () => {
  test.setTimeout(120000);
  if (!process.env.GYM_FLOOR_CDP_URL) throw Error('Use isolated gym-wave2-floor_items session, port 5316, and set GYM_FLOOR_CDP_URL.');
  const browser = await chromium.connectOverCDP(process.env.GYM_FLOOR_CDP_URL, {timeout:15000});
  console.log('CDP connected');
  const page = browser.contexts()[0].pages().find(p => p.url().includes(':5316/builder'))!;
  await page.setViewportSize({width:1280,height:633});
  await page.evaluate(() => localStorage.removeItem('bos-strength-configurations-v1'));
  await page.reload();
  const ready=()=>expect(page.getByRole('button',{name:'Export GLB ↗'})).toBeEnabled({timeout:30000});
  const floor=()=>page.evaluate(()=>{const data=JSON.parse(localStorage.getItem('bos-strength-configurations-v1') ?? '{}');return (data.draft ?? data.configs?.find((c:{id:string})=>c.id===data.activeId)?.doc)?.floorItems ?? [];});
  await ready();
  await page.getByRole('button',{name:/REP Nighthawk adjustable bench/}).click();
  await expect(page.getByRole('button',{name:'Place',exact:true})).toBeVisible();
  expect(await floor()).toEqual([]); // ghost has not mutated the document
  await page.getByRole('button',{name:'Place',exact:true}).click();await ready();
  await page.getByRole('button',{name:'Top',exact:true}).click();
  const original=(await floor())[0];expect(original.part).toBe('rep-nighthawk');
  await page.mouse.move(748,306);await page.mouse.down();await page.mouse.move(785,329);await page.mouse.move(820,355);await page.mouse.up();
  await expect.poll(async()=>JSON.stringify((await floor())[0].position)).not.toBe(JSON.stringify(original.position));
  const moved=(await floor())[0];expect(moved.position.every((n:number)=>n%25===0)).toBe(true);
  await page.keyboard.press('r');await expect.poll(async()=>(await floor())[0].rotation).toBeCloseTo(Math.PI/12);
  await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await floor())[0]).toEqual(moved);
  await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await floor())[0]).toEqual(original); // one undo for the whole drag
  await ready();
  await page.mouse.move(748,306);await page.mouse.down();await page.mouse.move(815,340);await page.keyboard.press('r');await page.keyboard.press('Escape');await page.mouse.up();
  await expect.poll(async()=>JSON.stringify((await floor())[0])).toBe(JSON.stringify(original));
  await expect(page.getByRole('button',{name:'Redo',exact:true})).toBeEnabled();
  await page.mouse.move(748,306);await page.mouse.down();await page.keyboard.down('Alt');await page.mouse.move(779,337);await page.mouse.up();await page.keyboard.up('Alt');
  await expect.poll(async()=>JSON.stringify((await floor())[0].position)).not.toBe(JSON.stringify(original.position));
  expect((await floor())[0].position.some((n:number)=>Math.abs(n/25-Math.round(n/25))>0.001)).toBe(true);
  await page.getByRole('button',{name:'Undo',exact:true}).click();await ready();
  await page.getByLabel('Backrest angle',{exact:true}).selectOption('85');
  await page.getByLabel('Seat angle',{exact:true}).selectOption('-15');
  await page.getByLabel('This piece steel finish',{exact:true}).selectOption('stainless');
  await page.getByLabel('Bench frame color',{exact:true}).selectOption('#24528a');
  expect((await floor())[0].params).toEqual({backrestAngle:85,seatAngle:-15});
  await page.getByRole('button',{name:'Reset Backrest angle',exact:true}).click();expect((await floor())[0].params).toEqual({backrestAngle:0,seatAngle:-15});
  await page.getByLabel('Backrest angle',{exact:true}).selectOption('60');
  await page.getByRole('button',{name:'Reset Seat angle',exact:true}).click();expect((await floor())[0].params).toEqual({backrestAngle:60,seatAngle:0});
  expect((await floor())[0].position).toEqual(original.position);expect((await floor())[0].rotation).toBe(original.rotation);
  await page.getByLabel('This piece steel finish',{exact:true}).selectOption('stainless');
  await page.getByRole('button',{name:'Reset bench frame color',exact:true}).click();
  await expect(page.getByLabel('This piece steel finish',{exact:true})).toHaveValue('stainless');
  await page.getByRole('button',{name:'Reset this bench',exact:true}).click();expect((await floor())[0].params).toEqual({backrestAngle:0,seatAngle:0});
  await page.getByLabel('Backrest angle',{exact:true}).selectOption('60');await page.getByLabel('Seat angle',{exact:true}).selectOption('-15');
  await page.locator('.config-manager summary').click();await page.getByLabel('Configuration name').fill('Nighthawk browser acceptance');await page.getByRole('button',{name:'Save configuration',exact:true}).click();
  await expect(page.locator('.config-manager summary')).not.toContainText('Unsaved');
  const saved=await floor();await page.reload();await ready();expect(await floor()).toEqual(saved);
  const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export GLB ↗'}).click();const download=await pending;
  const bytes=await fs.readFile((await download.path())!);const gltf=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());
  const bench=gltf.nodes.find((n:{extras?:{id:string}})=>n.extras?.id===saved[0].id);expect(bench.children).toHaveLength(7);expect(bench.extras.vendorAttribution.vendor).toBe('REP Fitness');
  const sources=bench.children.map((i:number)=>gltf.nodes[i].extras.materialSource);
  expect(sources.filter((s:{role:string;metalness:number})=>s.role==='liner').every((s:{metalness:number})=>s.metalness===0)).toBe(true);
  expect(sources.find((s:{role:string})=>s.role==='fastener').authoredFastenerFinish).toBe(true);
  await page.getByRole('button',{name:/Parts list \(/}).click();
  await page.locator('[data-instance-id="floor-1"]').click();
  await page.locator('[data-instance-id="front-left"]').click({modifiers:['Control']});
  await expect(page.getByRole('heading',{name:'2 parts',exact:true})).toBeVisible();
  await expect(page.getByLabel('Backrest angle',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Close ×',exact:true}).click();
  await page.getByRole('button',{name:'Remove parts',exact:true}).click();await ready();expect(await floor()).toEqual([]);
  await page.getByRole('button',{name:'Undo',exact:true}).click();await ready();expect(await floor()).toEqual(saved);
  await page.getByRole('button',{name:'Top',exact:true}).click();
  await page.getByRole('button',{name:/REP Nighthawk adjustable bench/}).click();
  await page.mouse.click(550,320);await ready();expect(await floor()).toHaveLength(2);
  await expect(page.getByText('Bench overlaps the rack footprint.',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Undo',exact:true}).click();await ready();expect(await floor()).toEqual(saved);
  // Keep the shared browser lifetime intact; this test only disconnects on process exit.
});
