import {test} from 'node:test';
import assert from 'node:assert/strict';
import {BuilderStore} from './builder-store.ts';
import {addAccessory, moveAccessory} from '../../rack-generator/assembly.ts';
import {barCradles} from '../../rack-generator/barbell-cradles.ts';
import type {PartId} from '../../rack-generator/types.ts';
const memory=()=>{const values=new Map<string,string>();return {getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}};};
const BAR='olympic-barbell' as PartId;
test('add barbell suggests the J-cups, hovers other cradles or the floor, parks once and persists',async()=>{
 const storage=memory(),store=new BuilderStore(storage);await store.ready;
 store.commit(addAccessory(store.getSnapshot().doc,'monolift',{uprightId:'front-left',face:'front',hole:18},true));
 const [monolift,jcups]=barCradles(store.getSnapshot().resolved).sort((a,b)=>a.center[2]-b.center[2]);
 store.startPlacement(BAR);
 let {proposal,placementText}=store.getSnapshot();
 assert.equal(proposal!.doc.floorItems![0].cradle,jcups.key);assert.match(placementText,/^Suggested: J-cups/);
 assert.ok(Math.abs(proposal!.entries[0].position[2]-(jcups.center[2]-28))<1e-9,'ghost sits in the cradle');
 store.previewFloor([500,-1200]);({proposal}=store.getSnapshot());
 assert.equal(proposal!.doc.floorItems![0].cradle,undefined);assert.equal(proposal!.entries[0].position[2],0);
 store.previewCradle(monolift.key);({proposal,placementText}=store.getSnapshot());
 assert.equal(proposal!.doc.floorItems![0].cradle,monolift.key);assert.match(placementText,/^Monolift arms/);
 store.previewFloor(undefined,Math.PI/12);assert.equal(store.getSnapshot().proposal,proposal,'R does not spin a parked bar');
 store.acceptProposal();
 const id=store.getSnapshot().selected!;assert.match(id,/^floor-/);
 assert.equal(store.getSnapshot().doc.floorItems![0].cradle,monolift.key);
 // One bar per cradle: a second bar suggests the free J-cups, and cannot take the monolift.
 store.startPlacement(BAR);assert.equal(store.getSnapshot().proposal!.doc.floorItems![1].cradle,jcups.key);
 store.previewCradle(monolift.key);assert.equal(store.getSnapshot().proposal!.doc.floorItems![1].cradle,jcups.key);
 store.escape();
 await store.save('Parked bar');await store.flushStorage();
 const restored=new BuilderStore(storage);await restored.ready;
 assert.deepEqual(restored.getSnapshot().doc.floorItems,store.getSnapshot().doc.floorItems);
 assert.equal(restored.getSnapshot().resolved.find(r=>r.id===id)!.position[2],monolift.center[2]-28);
});
test('double-click reposition re-parks in one undo; the bar follows its cradle and drops to the floor when it goes',async()=>{
 const store=new BuilderStore(memory());await store.ready;
 store.startPlacement(BAR);store.acceptProposal();
 const id=store.getSnapshot().selected!,parked=()=>store.getSnapshot().resolved.find(r=>r.id===id)!;
 const z=parked().position[2];
 store.pickup(id);assert.equal(store.getSnapshot().placing!.movingId,id);
 store.previewFloor([0,-1500]);store.acceptProposal();
 assert.equal(parked().position[2],0);assert.equal(store.getSnapshot().doc.floorItems![0].cradle,undefined);
 store.history('undo');assert.equal(parked().position[2],z);
 store.commit(moveAccessory(store.getSnapshot().doc,'jhooks-front',{hole:20}));
 assert.equal(parked().position[2],z-200,'follows the J-cups');
 const before=parked().position;
 store.select('jhooks-front:left');store.removeSelected();
 const floor=store.getSnapshot().doc.floorItems![0];
 assert.equal(floor.cradle,undefined);assert.deepEqual(floor.position,[before[0],-before[1]]);assert.equal(parked().position[2],0);
 assert.match(store.getSnapshot().status,/lost its cradle/);
 store.history('undo');assert.equal(parked().position[2],z-200,'one undo restores cradle and bar');
});
